### ISSUE TITLE
Wup Similarity does not work in certain cases

### ISSUE THREAD

**Issue by SoimulPatriei** [dumitrescustefan/RoWordNet#24]
Here is an example, where the similarity is computed for path and lch measures but crashes with wup similarity.

>>> wn.synset('ENG30-02962545-n').literals
['carte', 'carte_de_joc']
>>> wn.synset('ENG30-07051975-n').literals
['vorbe', 'text', 'versuri']

>> wn.path_similarity('ENG30-02962545-n','ENG30-07051975-n')
0.076

>>> wn.lch_similarity('ENG30-02962545-n','ENG30-07051975-n')
1.29

>>wn.wup_similarity ('ENG30-02962545-n','ENG30-07051975-n')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/eduardbarbu/anaconda3/lib/python3.6/site-packages/rowordnet/rowordnet.py", line 843, in wup_similarity
    depth_lcs_synset = len(self.synset_to_hypernym_root(lcs_synset))
  File "/Users/eduardbarbu/anaconda3/lib/python3.6/site-packages/rowordnet/rowordnet.py", line 624, in synset_to_hypernym_root
    .format(type(synset_id).__name__))
TypeError: Argument 'synset_id' has incorrect type, expected str, got NoneType

**Comment by avramandrei** [comment]
Hi, thank you for reporting this problem. I looked at the bug and it seems that the two synsets are not connected in the hypernym tree. I have modified the wup similarity to return None in such cases.

P.S.  if you want to use this feature, you should use the repository version until we update the API on pypi.

**Comment by SoimulPatriei** [comment]
Thanks for solving the bug very fast,
However, the behavior you implemented is not the one voted by the community. For the hierarchy of nouns, Princeton Wordnet has a node called **entity**, which is the root of the hierarchy.  Like the Romanian Wordnet, the hierarchy of verbs has no root. Therefore, the solution is this: "By default, there is now a fake root node added to verbs so for cases where previously a path could not be found---and None was returned---it should return a value." (see more here: https://www.nltk.org/howto/wordnet.html). 
I would think that this interface should follow the same policy as the **nltk** WordNet package. I would add two fake nodes for the hierarchies of nouns and verbs for similarity computation only. Of course, you might accept or not this solution, but by allowing it, you will make your interface conform to **nltk** behavior.

**Comment by dumitrescustefan** [comment]
I ran into this problem myself some years ago. I think this is an elegant solution around the multiple trees. We have to think if we need to simulate this only for sim measures (like doing sim on a copy of wn in the background with the verb root added) or add an actual extra common root for all verbs. What do you think Andrei? This one is on you ;)

What is the content of this virtual node in nltk?

**Comment by avramandrei** [comment]
This approach indeed looks very elegant. I will try to implement it in the following days and I will give a heads up when it is ready.

**Comment by avramandrei** [comment]
After I gave the implementation a thought, I have some some questions/suggestions:

1) I see that the two synsets you get the error from are nouns, not verbs, so that means that the nouns tree does not have a consistent root. I guess we should also add a virtual root for nouns.

2) I propose to simulate the virtual roots solution because I would not want to mess with the wn structure. Also, I do not think it is necessary to make a copy of the wn, we can add the virtual roots before computing the similarity measure and remove them afterwards. It should take O(1) time, given our implementation. 

3) Where should the virtual roots be added? As a root of all roots? Should the nouns and the verbs virtual roots be connected? If then, how so?

**Comment by SoimulPatriei** [comment]
If you want to keep the compatibility with **nltk** implementation you might do what I have proposed in the post above: " I would add two fake nodes for the hierarchies of nouns and verbs for similarity computation only.". It does not make sense to add one virtual node for both hierarchies because noun meaning and verb meanings are not related. What does it mean to say that the noun "cat" is similar to the verb "go"? It does not make sense. Whereas "cat" and "dog" are similar because they share all the properties of the upper node : "animal".

**Comment by avramandrei** [comment]
I have added a simulated root implementation for the wup similarity now on the github repository. This can be deactivated by setting the 'simulate_root' to False (as in nltk). Could you test it out and tell us if everything is ok? 

Thank you!

**Comment by SoimulPatriei** [comment]
Now it fails in another place. Here is the error :
wn.synset('ENG30-04548613-n').literals
['coșoroabă', 'iapă']
wn.synset('ENG30-03624767-n').literals
['cal']
wn.path_similarity('ENG30-03624767-n', 'ENG30-04548613-n')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/eduardbarbu/anaconda3/lib/python3.6/site-packages/rowordnet/rowordnet.py", line 807, in path_similarity
    shortest_path_distance = len(self.shortest_path(synset_id1, synset_id2, relations={"hypernym", "hyponym"}))
  File "/Users/eduardbarbu/anaconda3/lib/python3.6/site-packages/rowordnet/rowordnet.py", line 771, in shortest_path
    cur_synset_id = from_synset_id[cur_synset_id]
KeyError: 'ENG30-04548613-n'

**Comment by SoimulPatriei** [comment]
By the way I'm sharing with you a script you can run after you fix the bug. It takes 1000 word pairs, generates all the synsets for each pair. Then it computes all the three similarities (path, lch, wup) between the Cartesian product of the synsets. If the script passes it means that in what I'm concerned your interface works. https://drive.google.com/drive/folders/1WLrxAZvtI-Ce2eK7xOBYBN0z2hdNK9VE?usp=sharing
To run the script "**python wordnet_test.py**"

**Comment by avramandrei** [comment]
Thank you very much for sharing this testing script with us! I have corrected all the similarity metrics (it seems that all of them needed a simulated root), run the test script for quite a while and it looks okay. 

Could you confirm us that everything is working fine?

**Comment by SoimulPatriei** [comment]
Hi,
I've updated the API using pip install git+https://github.com/dumitrescustefan/RoWordNet.git but I get the same error as last time : KeyError: 'ENG30-04548613-n'

**Comment by avramandrei** [comment]
Are you sure you have the latest version installed? Try to uninstall it first and then reinstall it again from git. 

What is the similarity measure where it fails? On what synsets?

**Comment by SoimulPatriei** [comment]
As I said, it is the same error as above on the same synset. I will try to uninstall the old version and install the new from scratch, though until now I successfully updated all version with the command : git+https://github.com/dumitrescustefan/RoWordNet.git

**Comment by avramandrei** [comment]
Hmm, this is very weird. I have tried to reproduce the error, but it works well for me. Please let me know if uninstalling and reinstalling solved your problem. If it didn't, I will start further investigations.

Thank you!

**Comment by SoimulPatriei** [comment]
Ok,
I have uninstalled and reinstalled and I'm still running the script. I will let you know. However, the API is very slow. All the similarities for 1000 word pairs for English Wordnet lasts as long as the path similarity for the following two synsets in Romanian: wn.path_similarity('ENG30-03624767-n', 'ENG30-04548613-n')

**Comment by dumitrescustefan** [comment]
@SoimulPatriei is this safe to close? It is the same fix as that for #27 , if I'm not mistaking. Please confirm so we can close this as well.

**Comment by SoimulPatriei** [comment]
Yes. It is safe to close!
