### ISSUE TITLE
Python: Is there a way to automatically change diacritics?

### ISSUE THREAD

**Issue by me-suzy** [dumitrescustefan/RoWordNet#30]
for example this words:

strînsă -> strânsă
cîmp" -> câmp

Basically, I have words written in old style with  **_î_** instead of **_â_** And must replace this kind of discritics. Can this be done?

I believe, it is simple to do a code. Select all words that contain **_î_** anywhere in the words, except the beginning and end. Because words like **început, în, îl** must keep that **_î_** .

**Comment by dumitrescustefan** [comment]
I think this problem can be solved using a deterministic approach (i.e. change all î to â as long as they're not starting or ending a word, with a few other regexes to handle some exceptions). There are a lot of resources to do this (ex: https://www.dictie.ro/cand-scriem-cu-i-si-cand-scriem-cu-a/ ), and with a few rules like don't replace if î is prefixed by "ne" could get you 99% accuracy on this problem.

Regarding RoWordNet, it can't do this, it's not its purpose. But I guess maybe you could try to search for a literal with the above rule, and if you get a match then that's a valid word. However note that RoWordNet only has a small part of all Romanian words and can't handle inflexions, so better not go this route.
